### ISSUE TITLE
Name or service unknown

### ISSUE THREAD

**Issue by tdorzhi** [AxonIQ/axoniq-eventstore-client#9]
Can't test AxonDB connection in JUnit test with testcontainers.org

Sample code:
```
  private static EventStore eventStore;

  @ClassRule
  public static GenericContainer container = new GenericContainer("dorzhi/axondb")
      .withExposedPorts(8123, 8023)
      .withClasspathResourceMapping("axondb/axondb.properties", "/opt/axon/axondb.properties", BindMode.READ_WRITE);

  @BeforeClass
  public static void setUp() {
    Slf4jLogConsumer logConsumer = new Slf4jLogConsumer(log);
    container.followOutput(logConsumer);

    String hostPort = "localhost:" + container.getMappedPort(8123);

    log.info("Host and port: {}", hostPort);

    AxonDBConfiguration configuration = AxonDBConfiguration.newBuilder(hostPort).build();
    eventStore = new AxonDBEventStore(configuration, new JacksonSerializer());
  }

  @Test
  public void test() {
    eventStore.readEvents("id").forEachRemaining(m -> log.info("m: {}", m.getPayload()));
  }
```

fails with 

```
21:00:10.251 [grpc-default-executor-0] INFO  io.axoniq.axondb.client.AxonDBClient - Received: bb74323f8697:8123
Jul 19, 2018 9:00:10 PM io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl onError
WARNING: [io.grpc.internal.ManagedChannelImpl-5] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host bb74323f8697, cause=java.net.UnknownHostException: bb74323f8697: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at io.grpc.internal.DnsNameResolver$JdkResolver.resolve(DnsNameResolver.java:497)
	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
}
21:00:10.332 [grpc-default-executor-0] INFO  io.axoniq.axondb.client.AxonDBClient - Shutting down gRPC channel

org.axonframework.eventsourcing.eventstore.EventStoreException: io.axoniq.axondb.client.util.EventStoreClientException: UNAVAILABLE: Unable to resolve host bb74323f8697

	at io.axoniq.axondb.client.axon.AxonErrorMapping.convert(AxonErrorMapping.java:80)
	at io.axoniq.axondb.client.axon.AxonDBEventStore$AxonIQEventStorageEngine.readEventData(AxonDBEventStore.java:190)
	at org.axonframework.eventsourcing.eventstore.AbstractEventStorageEngine.readEvents(AbstractEventStorageEngine.java:97)
	at io.axoniq.axondb.client.axon.AxonDBEventStore$AxonIQEventStorageEngine.readEvents(AxonDBEventStore.java:271)
	at org.axonframework.eventsourcing.eventstore.AbstractEventStore.readEvents(AbstractEventStore.java:91)
	at jp.co.soramitsu.sora.reputation.integrationtests.UserRegisteredTest.test(UserRegisteredTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.ExecutionException: io.axoniq.axondb.client.util.EventStoreClientException: UNAVAILABLE: Unable to resolve host bb74323f8697
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.axoniq.axondb.client.AxonDBClient.listAggregateEvents(AxonDBClient.java:229)
	at io.axoniq.axondb.client.axon.AxonDBEventStore$AxonIQEventStorageEngine.readEventData(AxonDBEventStore.java:188)
	... 37 more
Caused by: io.axoniq.axondb.client.util.EventStoreClientException: UNAVAILABLE: Unable to resolve host bb74323f8697
	at io.axoniq.axondb.client.util.GrpcExceptionParser.parse(GrpcExceptionParser.java:40)
	at io.axoniq.axondb.client.AxonDBClient$2.onError(AxonDBClient.java:218)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host bb74323f8697
	at io.grpc.Status.asRuntimeException(Status.java:526)
	... 19 more
Caused by: java.net.UnknownHostException: bb74323f8697: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at io.grpc.internal.DnsNameResolver$JdkResolver.resolve(DnsNameResolver.java:497)
	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:200)
	... 3 more

21:00:10.343 [testcontainers-netty-1-12] ERROR org.testcontainers.shaded.io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dorg.testcontainers.shaded.io.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.
21:00:10.866 [Thread-1] INFO  org.springframework.context.support.GenericApplicationContext - Closing org.springframework.context.support.GenericApplicationContext@31024624: startup date [Thu Jul 19 21:00:09 MSK 2018]; root of context hierarchy

Process finished with exit code 255
```

**Comment by tdorzhi** [comment]
Resolved by setting this property axoniq.axondb.hostname=localhost

**Comment by javaHelper** [comment]
I am facing the same issue with 4.6.1 and I don't see setting `axoniq.axondb.hostname=localhost` works well.
